# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stencil < Formula
  desc "A modern living-template engine for evolving repositories"
  homepage "https://stencil.rgst.io"
  version "2.2.0"
  license "Apache-2.0"

  depends_on "git" if OS.mac?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rgst-io/stencil/releases/download/v2.2.0/stencil_2.2.0_darwin_amd64.tar.gz"
      sha256 "59bcdf38df1604223529dffcf9d76b71aff1d3866987e9a8af64df7721878a5e"

      def install
        bin.install "stencil"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rgst-io/stencil/releases/download/v2.2.0/stencil_2.2.0_darwin_arm64.tar.gz"
      sha256 "9e061dcc6a43812473473375067c42750fb9362c54d4efbce0ec41702c80aa7b"

      def install
        bin.install "stencil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rgst-io/stencil/releases/download/v2.2.0/stencil_2.2.0_linux_amd64.tar.gz"
        sha256 "f1c4504f93a73cf905a3ebc6120f903f43c0a6915ee43b2effc2cf6cb4fd9236"

        def install
          bin.install "stencil"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/rgst-io/stencil/releases/download/v2.2.0/stencil_2.2.0_linux_armv6.tar.gz"
        sha256 "d691e5e4d29d1754f528b988508f9e32cb9c3a02568e4c233d0567922d00dbca"

        def install
          bin.install "stencil"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rgst-io/stencil/releases/download/v2.2.0/stencil_2.2.0_linux_arm64.tar.gz"
        sha256 "5728b14f11578127d7771eb38f9baf18b97dec3fed611d006714c8cdbb3d2cc3"

        def install
          bin.install "stencil"
        end
      end
    end
  end

  conflicts_with "stencil"
end
